import { describe, expect, it } from 'vitest';
import { PRICING, priceFor } from '../../data/pricing';
import {
  calculateFinancing,
  calculateOption,
  cloneOptionForNewOption,
  createOptionInput,
  emptyVisitInput,
  isAutoGeneratedOptionName,
  nameForImplantBrand,
  type OptionInput,
  type ProcedureSelection,
} from './engine';

function baseOption(overrides: Partial<OptionInput> = {}): OptionInput {
  return { ...createOptionInput('opt-1', 'Test Option'), ...overrides };
}

/** A single-visit option with implant/crown/bridge quantities and (optionally) manual
 *  per-unit overrides so totals are exact, round numbers regardless of catalog markup. */
function treatmentOption(input: {
  implants: number;
  crowns: number;
  bridges?: number;
  implantUnitPrice?: number;
  crownUnitPrice?: number;
  bridgeUnitPrice?: number;
}): OptionInput {
  return baseOption({
    visits: 1,
    implant: { itemId: null, count: input.implants, markupPercent: 0, finalUnitPriceOverride: input.implantUnitPrice ?? 0 },
    crown: { itemId: null, count: input.crowns, markupPercent: 0, finalUnitPriceOverride: input.crownUnitPrice ?? 0 },
    bridge: { itemId: null, count: input.bridges ?? 0, markupPercent: 0, finalUnitPriceOverride: input.bridgeUnitPrice ?? 0 },
    visit1: emptyVisitInput(),
    visit2: null,
  });
}

// ===========================================================================
// §1-4 — no All-on-X, implants/crowns/bridge fully independent
// ===========================================================================

describe('implant/crown/bridge quantities are independent (§1-4, §23 #1-6)', () => {
  it('1: 4 implants + 28 crowns is valid', () => {
    const result = calculateOption(treatmentOption({ implants: 4, crowns: 28, implantUnitPrice: 300, crownUnitPrice: 150 }), 'USD', 1);
    expect(result.treatment.implants.quantity).toBe(4);
    expect(result.treatment.crowns.quantity).toBe(28);
  });

  it('2: 4 implants + 12 crowns is valid', () => {
    const result = calculateOption(treatmentOption({ implants: 4, crowns: 12, implantUnitPrice: 300, crownUnitPrice: 150 }), 'USD', 1);
    expect(result.treatment.implants.quantity).toBe(4);
    expect(result.treatment.crowns.quantity).toBe(12);
  });

  it('3: 6 implants + 24 crowns is valid', () => {
    const result = calculateOption(treatmentOption({ implants: 6, crowns: 24, implantUnitPrice: 300, crownUnitPrice: 150 }), 'USD', 1);
    expect(result.treatment.implants.quantity).toBe(6);
    expect(result.treatment.crowns.quantity).toBe(24);
  });

  it('4: 8 implants + 28 crowns is valid', () => {
    const result = calculateOption(treatmentOption({ implants: 8, crowns: 28, implantUnitPrice: 300, crownUnitPrice: 150 }), 'USD', 1);
    expect(result.treatment.implants.quantity).toBe(8);
    expect(result.treatment.crowns.quantity).toBe(28);
  });

  it('10 implants + 28 crowns is valid (no coupling caps the ratio)', () => {
    const result = calculateOption(treatmentOption({ implants: 10, crowns: 28, implantUnitPrice: 300, crownUnitPrice: 150 }), 'USD', 1);
    expect(result.treatment.implants.quantity).toBe(10);
    expect(result.treatment.crowns.quantity).toBe(28);
  });

  it('5: crown quantity never equals or derives from implant quantity', () => {
    const a = calculateOption(treatmentOption({ implants: 4, crowns: 12, implantUnitPrice: 300, crownUnitPrice: 150 }), 'USD', 1);
    const b = calculateOption(treatmentOption({ implants: 4, crowns: 28, implantUnitPrice: 300, crownUnitPrice: 150 }), 'USD', 1);
    expect(a.treatment.implants.quantity).toBe(b.treatment.implants.quantity); // same implants
    expect(a.treatment.crowns.quantity).not.toBe(b.treatment.crowns.quantity); // different crowns
    expect(a.treatment.crowns.quantity).not.toBe(a.treatment.implants.quantity); // never forced equal
  });

  it('6: bridge quantity is set independently and never auto-added because implants exist', () => {
    const noBridge = calculateOption(treatmentOption({ implants: 4, crowns: 12, bridges: 0, implantUnitPrice: 300 }), 'USD', 1);
    expect(noBridge.treatment.bridge.quantity).toBe(0);
    expect(noBridge.treatment.bridge.total).toBe(0);

    const withBridge = calculateOption(treatmentOption({ implants: 6, crowns: 24, bridges: 2, bridgeUnitPrice: 1000 }), 'USD', 1);
    expect(withBridge.treatment.bridge.quantity).toBe(2);

    // A brand-new option (nothing entered) never has a bridge — it is never created
    // automatically just because implants/crowns are present.
    const fresh = createOptionInput('fresh', 'Fresh');
    expect(fresh.bridge.count).toBe(0);
    expect(fresh.bridge.itemId).toBeNull();
  });

  it('valid combinations from the brief: 4+12+1, 4+28+0, 6+24+2', () => {
    for (const c of [
      { implants: 4, crowns: 12, bridges: 1 },
      { implants: 4, crowns: 28, bridges: 0 },
      { implants: 6, crowns: 24, bridges: 2 },
    ]) {
      const result = calculateOption(treatmentOption({ ...c, implantUnitPrice: 300, crownUnitPrice: 150, bridgeUnitPrice: 1000 }), 'USD', 1);
      expect(result.treatment.implants.quantity).toBe(c.implants);
      expect(result.treatment.crowns.quantity).toBe(c.crowns);
      expect(result.treatment.bridge.quantity).toBe(c.bridges);
    }
  });

  it('7/8/9: implant, crown and bridge totals are each quantity x their own unit price', () => {
    const result = calculateOption(
      treatmentOption({ implants: 5, crowns: 18, bridges: 2, implantUnitPrice: 640, crownUnitPrice: 155, bridgeUnitPrice: 1000 }),
      'USD',
      1,
    );
    expect(result.treatment.implants.total).toBe(5 * 640);
    expect(result.treatment.crowns.total).toBe(18 * 155);
    expect(result.treatment.bridge.total).toBe(2 * 1000);
    // Changing crown quantity must not move implant/bridge totals.
    const changedCrowns = calculateOption(
      treatmentOption({ implants: 5, crowns: 99, bridges: 2, implantUnitPrice: 640, crownUnitPrice: 155, bridgeUnitPrice: 1000 }),
      'USD',
      1,
    );
    expect(changedCrowns.treatment.implants.total).toBe(result.treatment.implants.total);
    expect(changedCrowns.treatment.bridge.total).toBe(result.treatment.bridge.total);
  });
});

// ===========================================================================
// §10-11, §23 #10 — multi-currency independence
// ===========================================================================

describe('multi-currency independence (§10-11)', () => {
  it('10: USD/EUR/AUD prices are independent — never converted from one another', () => {
    const medigma = PRICING.implants.find((i) => i.id === 'medigma')!;
    expect(medigma.price.usd).toBe(300);
    expect(medigma.price.eur).toBeNull(); // not configured — must not be invented

    const option = treatmentOption({ implants: 2, crowns: 0 });
    option.implant.itemId = 'medigma';
    option.implant.finalUnitPriceOverride = null;

    const eur = calculateOption(option, 'EUR', 1.1567); // a real-looking rate — must be ignored
    expect(eur.treatment.implants.priceConfigured).toBe(false);
    expect(eur.treatment.implants.total).toBe(0);
    expect(eur.treatment.implants.total).not.toBeCloseTo(2 * 300 * 1.1567, 2);
  });

  it('a manual override belongs to the selected currency and is never converted', () => {
    const option = treatmentOption({ implants: 1, crowns: 0, implantUnitPrice: 900 }); // AUD override
    const result = calculateOption(option, 'AUD', 1.52);
    expect(result.treatment.implants.finalUnitPrice).toBe(900);
    expect(result.treatment.implants.total).toBe(900);
  });

  it('11: USD equivalent (fxRate) never changes the primary calculated amount', () => {
    const option = treatmentOption({ implants: 3, crowns: 0, implantUnitPrice: 550 }); // EUR price
    const cheap = calculateOption(option, 'EUR', 0.0001);
    const expensive = calculateOption(option, 'EUR', 999);
    expect(cheap.treatment.implants.total).toBe(1650);
    expect(expensive.treatment.implants.total).toBe(1650);
  });
});

// ===========================================================================
// §12 — procedure/unit price overrides
// ===========================================================================

describe('procedure/unit price overrides (§12, §23 #11)', () => {
  it('11: override REPLACES the calculated unit price — never added to it', () => {
    const option = baseOption({
      visits: 1,
      implant: { itemId: 'medigma', count: 2, markupPercent: 25, finalUnitPriceOverride: 280 }, // catalog $300*1.25=375, override 280
      visit1: emptyVisitInput(),
      visit2: null,
    });
    const result = calculateOption(option, 'USD', 1);
    expect(result.treatment.implants.finalUnitPrice).toBe(280); // not 375, and not 375+280
    expect(result.treatment.implants.total).toBe(2 * 280); // lineTotal = quantity * finalUnitPrice
  });
});

// ===========================================================================
// §13-14, §23 #12-14 — per-visit overrides
// ===========================================================================

describe('per-visit overrides (§13-14)', () => {
  it('12/13: visit1 override affects visit1 only; visit2 override affects visit2 only', () => {
    const option = baseOption({
      visits: 2,
      implant: { itemId: null, count: 1, markupPercent: 0, finalUnitPriceOverride: 6500 }, // visit 1 (default split)
      crown: { itemId: null, count: 1, markupPercent: 0, finalUnitPriceOverride: 3500 }, // visit 2 (default split)
      visit1CrownCount: 0,
      visit1: { ...emptyVisitInput(), overrideTotal: 5900 },
      visit2: { ...emptyVisitInput(), overrideTotal: null },
    });
    const result = calculateOption(option, 'EUR', 1);
    expect(result.visits.visit1.calculatedTotal).toBe(6500);
    expect(result.visits.visit1.finalTotal).toBe(5900); // overridden
    expect(result.visits.visit2!.calculatedTotal).toBe(3500);
    expect(result.visits.visit2!.finalTotal).toBe(3500); // untouched by visit1's override

    const onlyVisit2 = baseOption({
      ...option,
      visit1: { ...emptyVisitInput(), overrideTotal: null },
      visit2: { ...emptyVisitInput(), overrideTotal: 3200 },
    });
    const result2 = calculateOption(onlyVisit2, 'EUR', 1);
    expect(result2.visits.visit1.finalTotal).toBe(6500); // untouched by visit2's override
    expect(result2.visits.visit2!.finalTotal).toBe(3200);
  });

  it('14: plan total = sum of FINAL visit totals, never calculated totals, never a whole-plan override', () => {
    const option = baseOption({
      visits: 2,
      implant: { itemId: null, count: 1, markupPercent: 0, finalUnitPriceOverride: 7000 },
      crown: { itemId: null, count: 1, markupPercent: 0, finalUnitPriceOverride: 4000 },
      visit1CrownCount: 0,
      visit1: { ...emptyVisitInput(), overrideTotal: 6000 },
      visit2: { ...emptyVisitInput(), overrideTotal: null },
    });
    const result = calculateOption(option, 'EUR', 1);
    expect(result.totals.calculatedTotal).toBe(11000);
    expect(result.totals.finalTotal).toBe(10000); // 6000 + 4000
    expect(result.totals.total).toBe(result.visits.visit1.finalTotal + result.visits.visit2!.finalTotal);
  });
});

// ===========================================================================
// §14-19, §23 #15-21 — flight ticket
// ===========================================================================

describe('flight ticket (§14-19)', () => {
  it('15/16: can be entered, and is optional (no field means no cost)', () => {
    const withTicket = baseOption({ visits: 1, visit1: emptyVisitInput(), visit2: null, flightTicket: { amount: 650 } });
    const withoutTicket = baseOption({ visits: 1, visit1: emptyVisitInput(), visit2: null, flightTicket: { amount: null } });
    expect(calculateOption(withTicket, 'EUR', 1).totals.flightTicket).toBe(650);
    expect(calculateOption(withoutTicket, 'EUR', 1).totals.flightTicket).toBe(0);
  });

  it('17: flight ticket is added to the final quotation total', () => {
    const option = baseOption({
      visits: 1,
      implant: { itemId: null, count: 1, markupPercent: 0, finalUnitPriceOverride: 9500 },
      visit1: emptyVisitInput(),
      visit2: null,
      flightTicket: { amount: 650 },
    });
    const result = calculateOption(option, 'EUR', 1);
    expect(result.totals.calculatedTotal).toBe(10150);
    expect(result.totals.finalTotal).toBe(10150);
  });

  it('18/19: flight ticket uses the selected currency directly — no conversion', () => {
    const eurOption = baseOption({ visits: 1, visit1: emptyVisitInput(), visit2: null, flightTicket: { amount: 650 } });
    const audOption = baseOption({ visits: 1, visit1: emptyVisitInput(), visit2: null, flightTicket: { amount: 1050 } });
    const usdOption = baseOption({ visits: 1, visit1: emptyVisitInput(), visit2: null, flightTicket: { amount: 700 } });

    expect(calculateOption(eurOption, 'EUR', 1).totals.flightTicket).toBe(650);
    expect(calculateOption(audOption, 'AUD', 1).totals.flightTicket).toBe(1050);
    expect(calculateOption(usdOption, 'USD', 1).totals.flightTicket).toBe(700);

    // A deliberately "wrong" fxRate must have zero effect on the entered amount.
    expect(calculateOption(eurOption, 'EUR', 999).totals.flightTicket).toBe(650);
    expect(calculateOption(eurOption, 'EUR', 0.0001).totals.flightTicket).toBe(650);
  });

  it('20: no flight ticket entered means no additional cost, and generation is never blocked', () => {
    const option = baseOption({
      visits: 1,
      implant: { itemId: null, count: 1, markupPercent: 0, finalUnitPriceOverride: 1000 },
      visit1: emptyVisitInput(),
      visit2: null,
      flightTicket: { amount: null },
    });
    const result = calculateOption(option, 'USD', 1);
    expect(result.totals.flightTicket).toBe(0);
    expect(result.totals.finalTotal).toBe(1000); // unchanged by the absent flight ticket
  });

  it('21: the printed total (what the PDF renders) reflects the flight ticket', () => {
    // generateSimpleQuotationPdf / generatePremiumQuotationPdf render option.totals.total and,
    // when > 0, a dedicated "Flight ticket" row from option.totals.flightTicket (see those
    // files) — this asserts the exact numbers those templates consume.
    const option = baseOption({
      visits: 1,
      implant: { itemId: null, count: 1, markupPercent: 0, finalUnitPriceOverride: 9500 },
      visit1: emptyVisitInput(),
      visit2: null,
      flightTicket: { amount: 650 },
    });
    const result = calculateOption(option, 'EUR', 1);
    expect(result.totals.flightTicket).toBe(650);
    expect(result.totals.total).toBe(10150);
  });

  it('flight ticket is never confused with a procedure/visit override or a discount', () => {
    const option = baseOption({
      visits: 1,
      implant: { itemId: null, count: 1, markupPercent: 0, finalUnitPriceOverride: 1000 },
      visit1: { ...emptyVisitInput(), overrideTotal: 800 }, // an unrelated visit override
      visit2: null,
      flightTicket: { amount: 200 },
    });
    const result = calculateOption(option, 'USD', 1);
    expect(result.visits.visit1.finalTotal).toBe(800); // visit override still just replaces
    expect(result.totals.finalTotal).toBe(1000); // 800 (visit final) + 200 (flight ticket), additive
  });
});

// ===========================================================================
// Regression: bridge quantity x unit price, currency-independent (still true)
// ===========================================================================

describe('bridge pricing (§2 previously, still applicable)', () => {
  it('bridgeTotal = bridgeUnitPrice x bridgeQuantity, and AUD is never assumed from USD/EUR', () => {
    const bridge = PRICING.bridges.find((b) => b.id === 'full-arch-bridge')!;
    expect(bridge.price).toEqual({ usd: 1000, eur: 1000, aud: null });

    const twoArches = treatmentOption({ implants: 0, crowns: 0, bridges: 2 });
    twoArches.bridge.itemId = 'full-arch-bridge';
    twoArches.bridge.finalUnitPriceOverride = null;

    expect(calculateOption(twoArches, 'USD', 1).treatment.bridge.total).toBe(2000);
    expect(calculateOption(twoArches, 'EUR', 1).treatment.bridge.total).toBe(2000);
    expect(calculateOption(twoArches, 'AUD', 1).treatment.bridge.total).toBe(0);
    expect(calculateOption(twoArches, 'AUD', 1).treatment.bridge.priceConfigured).toBe(false);
  });
});

// ===========================================================================
// Implant country-of-origin passthrough (for the PDF brand/origin display)
// ===========================================================================

// ===========================================================================
// US/Canada installment financing — the markup applies ONLY to the financed amount
// (installmentBase, capped at PRICING.financing.installmentAmount / $3900), never to the
// whole treatment total. See calculateFinancing's own doc comment for the bug this fixes.
// ===========================================================================

describe('calculateFinancing', () => {
  it('not eligible (wrong country or payment method) -> everything zero', () => {
    const option = calculateOption(treatmentOption({ implants: 1, crowns: 0, implantUnitPrice: 10000 }), 'USD', 1);
    expect(calculateFinancing(option, 'France', 'installments').eligible).toBe(false);
    expect(calculateFinancing(option, 'United States', 'visit-payments').eligible).toBe(false);
    expect(calculateFinancing(option, 'France', 'installments')).toMatchObject({ financedPackage: 0, installmentBase: 0, installment: 0, cashRemaining: 0, cashPerVisit: 0 });
  });

  it('CRITICAL: the markup applies ONLY to the financed amount (capped at $3900), never the whole treatment total', () => {
    const option = calculateOption(treatmentOption({ implants: 1, crowns: 0, implantUnitPrice: 10000 }), 'USD', 1);
    const f = calculateFinancing(option, 'United States', 'installments');

    expect(PRICING.financing.installmentAmount).toBe(3900); // the clinic maximum this test assumes
    expect(PRICING.financing.markupPercent).toBe(20);

    expect(f.installmentBase).toBe(3900); // no explicit request -> defaults to the clinic max
    expect(f.installment).toBe(4680); // 3900 * 1.20 — the markup on the FINANCED amount only
    expect(f.cashRemaining).toBe(6100); // 10000 - 3900, at face value, no markup
    expect(f.financedPackage).toBe(10780); // 4680 + 6100
    expect(f.financedPackage).not.toBe(12000); // the old (wrong) 10000 * 1.20 behaviour
  });

  it('a patient approved for less than the clinic max finances that lower amount instead', () => {
    const option = calculateOption(treatmentOption({ implants: 1, crowns: 0, implantUnitPrice: 10000 }), 'USD', 1);
    const f = calculateFinancing(option, 'Canada', 'installments', 2500);
    expect(f.installmentBase).toBe(2500);
    expect(f.installment).toBe(3000); // 2500 * 1.20
    expect(f.cashRemaining).toBe(7500); // 10000 - 2500
    expect(f.financedPackage).toBe(10500);
  });

  it('a requested amount above the clinic max is clamped down to the max, never honoured as-is', () => {
    const option = calculateOption(treatmentOption({ implants: 1, crowns: 0, implantUnitPrice: 10000 }), 'USD', 1);
    const f = calculateFinancing(option, 'United States', 'installments', 6000);
    expect(f.installmentBase).toBe(3900);
    expect(f.installment).toBe(4680);
  });

  it('cannot finance more than the treatment actually costs, even under the clinic max', () => {
    const option = calculateOption(treatmentOption({ implants: 1, crowns: 0, implantUnitPrice: 2000 }), 'USD', 1);
    const f = calculateFinancing(option, 'United States', 'installments'); // defaults to the $3900 max
    expect(f.installmentBase).toBe(2000); // clamped to the total, not 3900
    expect(f.installment).toBe(2400); // 2000 * 1.20
    expect(f.cashRemaining).toBe(0);
    expect(f.financedPackage).toBe(2400);
  });

  it('an invalid/negative requested amount falls back to the clinic max, not to 0', () => {
    const option = calculateOption(treatmentOption({ implants: 1, crowns: 0, implantUnitPrice: 10000 }), 'USD', 1);
    expect(calculateFinancing(option, 'United States', 'installments', -500).installmentBase).toBe(3900);
    expect(calculateFinancing(option, 'United States', 'installments', null).installmentBase).toBe(3900);
  });

  it('cashRemaining splits evenly across visits; a single visit gets it all', () => {
    const twoVisit = baseOption({
      visits: 2,
      implant: { itemId: null, count: 1, markupPercent: 0, finalUnitPriceOverride: 10000 },
      visit1CrownCount: 0,
      visit1: { ...emptyVisitInput(), overrideTotal: null },
      visit2: { ...emptyVisitInput(), overrideTotal: null },
    });
    const result = calculateOption(twoVisit, 'USD', 1);
    const f = calculateFinancing(result, 'United States', 'installments');
    expect(f.cashRemaining).toBe(6100);
    expect(f.cashPerVisit).toBe(3050); // split across 2 visits

    const oneVisit = calculateOption(treatmentOption({ implants: 1, crowns: 0, implantUnitPrice: 10000 }), 'USD', 1);
    const f2 = calculateFinancing(oneVisit, 'United States', 'installments');
    expect(f2.cashPerVisit).toBe(f2.cashRemaining);
  });
});

// ===========================================================================
// Adding a new option copies quantities/hotel/nights/transfer from the previous one, but
// never brand choices or manual price overrides — and the option auto-names itself after the
// implant brand's country of origin.
// ===========================================================================

describe('cloneOptionForNewOption', () => {
  function fullyLoadedOption(): OptionInput {
    return {
      id: 'opt-1',
      name: 'Option 1',
      implant: { itemId: 'straumann', count: 4, markupPercent: 30, finalUnitPriceOverride: 700 },
      crown: { itemId: 'ivoclar-zirconia', count: 24, markupPercent: 30, finalUnitPriceOverride: 120 },
      bridge: { itemId: 'full-arch-bridge', count: 1, markupPercent: 15, finalUnitPriceOverride: 900 },
      procedures: [{ procedureId: 'bone-graft', quantity: 2, finalUnitPriceOverride: 300 }],
      visits: 2,
      visit1CrownCount: 12,
      visit1: {
        hotel: { hotelId: 'hotel-a', roomType: 'double', nights: 5, nightlyPriceOverride: 85 },
        transfer: { selectedUsd: 150, finalPriceOverride: 100 },
        prosthesis: { selectedUsd: 200, finalPriceOverride: 180 },
        overrideTotal: 5900,
      },
      visit2: {
        hotel: { hotelId: 'hotel-b', roomType: 'single', nights: 2, nightlyPriceOverride: null },
        transfer: { selectedUsd: 0, finalPriceOverride: null },
        prosthesis: { selectedUsd: 0, finalPriceOverride: null },
        overrideTotal: null,
      },
      flightTicket: { amount: 650 },
    };
  }

  it('copies quantities, visit structure, hotel selection/nights, and service selections', () => {
    const clone = cloneOptionForNewOption(fullyLoadedOption(), 'opt-2', 'Option 2');
    expect(clone.implant.count).toBe(4);
    expect(clone.crown.count).toBe(24);
    expect(clone.bridge.count).toBe(1);
    expect(clone.visits).toBe(2);
    expect(clone.visit1CrownCount).toBe(12);
    expect(clone.visit1.hotel.hotelId).toBe('hotel-a');
    expect(clone.visit1.hotel.roomType).toBe('double');
    expect(clone.visit1.hotel.nights).toBe(5);
    expect(clone.visit1.transfer.selectedUsd).toBe(150);
    expect(clone.visit1.prosthesis.selectedUsd).toBe(200);
    expect(clone.visit2!.hotel.hotelId).toBe('hotel-b');
    expect(clone.visit2!.hotel.nights).toBe(2);
  });

  it('CRITICAL: never copies brand/material choices or any manual price override', () => {
    const clone = cloneOptionForNewOption(fullyLoadedOption(), 'opt-2', 'Option 2');
    expect(clone.implant.itemId).toBeNull();
    expect(clone.implant.finalUnitPriceOverride).toBeNull();
    expect(clone.crown.itemId).toBeNull();
    expect(clone.crown.finalUnitPriceOverride).toBeNull();
    expect(clone.bridge.itemId).toBeNull();
    expect(clone.bridge.finalUnitPriceOverride).toBeNull();
    expect(clone.visit1.hotel.nightlyPriceOverride).toBeNull();
    expect(clone.visit1.transfer.finalPriceOverride).toBeNull();
    expect(clone.visit1.prosthesis.finalPriceOverride).toBeNull();
    expect(clone.visit1.overrideTotal).toBeNull();
    expect(clone.visit2!.hotel.nightlyPriceOverride).toBeNull();
  });

  it('preserves markup percentages (a rate, not a one-off override)', () => {
    const clone = cloneOptionForNewOption(fullyLoadedOption(), 'opt-2', 'Option 2');
    expect(clone.implant.markupPercent).toBe(30);
    expect(clone.crown.markupPercent).toBe(30);
    expect(clone.bridge.markupPercent).toBe(15);
  });

  it('does not copy additional procedures or the flight ticket', () => {
    const clone = cloneOptionForNewOption(fullyLoadedOption(), 'opt-2', 'Option 2');
    expect(clone.procedures).toEqual([]);
    expect(clone.flightTicket.amount).toBeNull();
  });

  it('a single-visit source (visit2 null) stays single-visit', () => {
    const source = { ...fullyLoadedOption(), visits: 1 as const, visit2: null };
    const clone = cloneOptionForNewOption(source, 'opt-2', 'Option 2');
    expect(clone.visit2).toBeNull();
  });

  it('uses the given id/name, not the source option’s', () => {
    const clone = cloneOptionForNewOption(fullyLoadedOption(), 'opt-2', 'Option 2');
    expect(clone.id).toBe('opt-2');
    expect(clone.name).toBe('Option 2');
  });
});

describe('implant-brand option naming', () => {
  it('maps known catalog origins to their bare nationality name', () => {
    expect(nameForImplantBrand('medigma')).toBe('German'); // matches the user's own example
    expect(nameForImplantBrand('straumann')).toBe('Swiss'); // matches the user's own example
    expect(nameForImplantBrand('hiossen')).toBe('American');
    expect(nameForImplantBrand('megagen')).toBe('Korean');
    expect(nameForImplantBrand('venus')).toBe('Turkish');
  });

  it('"Other"-origin brands and no selection do not produce a name', () => {
    expect(nameForImplantBrand('nobel-biocare')).toBeNull(); // origin: 'Other'
    expect(nameForImplantBrand(null)).toBeNull();
    expect(nameForImplantBrand('not-a-real-id')).toBeNull();
  });

  it('every implant in the catalog resolves through the SAME id used to price it', () => {
    for (const implant of PRICING.implants) {
      const name = nameForImplantBrand(implant.id);
      if (implant.origin === 'Other') expect(name).toBeNull();
      else expect(name).toBe(implant.origin);
    }
  });

  it('isAutoGeneratedOptionName recognises the default "Option N" pattern and bare origin names', () => {
    expect(isAutoGeneratedOptionName('Option 1')).toBe(true);
    expect(isAutoGeneratedOptionName('Option 12')).toBe(true);
    expect(isAutoGeneratedOptionName('German')).toBe(true);
    expect(isAutoGeneratedOptionName('Swiss')).toBe(true);
  });

  it('isAutoGeneratedOptionName is false for a name the coordinator actually typed', () => {
    expect(isAutoGeneratedOptionName('Budget Package')).toBe(false);
    expect(isAutoGeneratedOptionName('Premium Option')).toBe(false);
    expect(isAutoGeneratedOptionName('')).toBe(false);
  });
});

describe('implant origin passthrough', () => {
  it('a selected implant carries its catalog origin', () => {
    const straumann = PRICING.implants.find((i) => i.id === 'straumann')!;
    expect(straumann.origin).toBe('Swiss');

    const option = treatmentOption({ implants: 1, crowns: 0 });
    option.implant.itemId = 'straumann';
    const result = calculateOption(option, 'USD', 1);
    expect(result.treatment.implants.origin).toBe('Swiss');
  });

  it('crowns/bridges never carry an origin (no such catalog field) — always null', () => {
    const option = treatmentOption({ implants: 0, crowns: 1, bridges: 1 });
    option.crown.itemId = PRICING.crowns[0].id;
    option.bridge.itemId = PRICING.bridges[0].id;
    const result = calculateOption(option, 'USD', 1);
    expect(result.treatment.crowns.origin).toBeNull();
    expect(result.treatment.bridge.origin).toBeNull();
  });

  it('no implant selected -> origin is null', () => {
    const result = calculateOption(treatmentOption({ implants: 0, crowns: 0 }), 'USD', 1);
    expect(result.treatment.implants.origin).toBeNull();
  });
});

// ===========================================================================
// Bariatric + Plastic/Aesthetic catalog — extends PRICING.procedures /
// ProcedureSelection / calculateOption(), the same pipeline the original dental
// add-on procedures already used. See src/data/pricing.ts and OptionCard.tsx.
// ===========================================================================

/** A single-visit option carrying only the given procedure selections — everything else
 *  (implants/crowns/bridge/hotel) left at zero/empty so the procedures total is exact. */
function procedureOption(selections: ProcedureSelection[]): OptionInput {
  return baseOption({ visits: 1, procedures: selections, visit1: emptyVisitInput(), visit2: null });
}

describe('Bariatric + Plastic/Aesthetic catalog', () => {
  it('1: Gastric Sleeve has a fixed EUR catalog price of €2,700 (no USD/AUD configured)', () => {
    const item = PRICING.procedures.find((p) => p.id === 'gastric_sleeve')!;
    expect(item.price.eur).toBe(2700);
    expect(item.price.usd).toBeNull();
    expect(item.price.aud).toBeNull();
    expect(item.category).toBe('Bariatric');
  });

  it('2: Gastric Balloon exposes a €1,300–€4,000 reference range and no fixed price', () => {
    const item = PRICING.procedures.find((p) => p.id === 'gastric_balloon')!;
    expect(item.priceRange).toEqual({ min: 1300, max: 4000 });
    expect(item.price.eur).toBeNull();
    expect(item.price.usd).toBeNull();
    expect(item.price.aud).toBeNull();
  });

  it('3: Gastric Band has no catalog price in any currency', () => {
    const item = PRICING.procedures.find((p) => p.id === 'gastric_band')!;
    expect(item.price).toEqual({ usd: null, eur: null, aud: null });
    expect(item.priceRange).toBeUndefined();
  });

  it('4: Arm Lifting / Brachioplasty has no catalog price', () => {
    const item = PRICING.procedures.find((p) => p.id === 'arm_lifting')!;
    expect(item.price).toEqual({ usd: null, eur: null, aud: null });
  });

  it('5: a coordinator-entered price for an unpriced procedure is the price actually billed', () => {
    const option = procedureOption([{ procedureId: 'arm_lifting', quantity: 1, finalUnitPriceOverride: 2450 }]);
    const result = calculateOption(option, 'EUR', 1);
    expect(result.treatment.procedures[0].total).toBe(2450);
    expect(result.treatment.procedures[0].priceConfigured).toBe(true);
  });

  it('6: a missing catalog price NEVER becomes 0 while unpriced — it is flagged priceConfigured=false, and total is 0 ONLY because nothing was entered, not silently accepted as a real $0/€0 price', () => {
    const option = procedureOption([{ procedureId: 'arm_lifting', quantity: 1, finalUnitPriceOverride: null }]);
    const result = calculateOption(option, 'EUR', 1);
    expect(result.treatment.procedures[0].priceConfigured).toBe(false);
    expect(result.treatment.procedures[0].total).toBe(0);
    expect(result.treatment.procedures[0].manualUnitPrice).toBeNull();
  });

  it('7: EUR pricing is never derived from USD — Gastric Sleeve has no USD price, so viewing in USD leaves it unconfigured rather than converting the EUR figure', () => {
    const option = procedureOption([{ procedureId: 'gastric_sleeve', quantity: 1, finalUnitPriceOverride: null }]);
    const usdResult = calculateOption(option, 'USD', 1);
    expect(usdResult.treatment.procedures[0].priceConfigured).toBe(false);
    expect(usdResult.treatment.procedures[0].total).toBe(0);

    const eurResult = calculateOption(option, 'EUR', 1);
    expect(eurResult.treatment.procedures[0].priceConfigured).toBe(true);
    expect(eurResult.treatment.procedures[0].total).toBe(2700);
  });

  it('8: USD/AUD remain unconfigured for every newly added Bariatric/Plastic entry unless independently supplied', () => {
    const newCatalogIds = [
      'gastric_sleeve', 'gastric_bypass', 'gastric_mini_bypass', 'sadi_s', 'bari_clip',
      'rhinoplasty', 'blepharoplasty', 'septoplasty', 'labiaplasty', 'jaw_silicone',
    ];
    for (const id of newCatalogIds) {
      const item = PRICING.procedures.find((p) => p.id === id)!;
      expect(item.price.usd, `${id} usd`).toBeNull();
      expect(item.price.aud, `${id} aud`).toBeNull();
      expect(item.price.eur, `${id} eur`).not.toBeNull();
    }
  });

  it('9: J-Plasma has no standalone price in any currency and carries its combination note', () => {
    const item = PRICING.procedures.find((p) => p.id === 'j_plasma')!;
    expect(item.price).toEqual({ usd: null, eur: null, aud: null });
    expect(item.note).toMatch(/combined with liposuction/i);
  });

  it('10: the priced Liposuction + J-Plasma combination is its own €3,600 catalog entry', () => {
    const item = PRICING.procedures.find((p) => p.id === 'liposuction_jplasma_combo')!;
    expect(item.price.eur).toBe(3600);
    const option = procedureOption([{ procedureId: 'liposuction_jplasma_combo', quantity: 1, finalUnitPriceOverride: null }]);
    const result = calculateOption(option, 'EUR', 1);
    expect(result.treatment.procedures[0].total).toBe(3600);
    expect(result.treatment.procedures[0].priceConfigured).toBe(true);
  });

  it('11: NOT-DONE procedures (Cat Eyes / Fox Eyes, Lip Lifting) are flagged unavailable so the UI can never let them be selected', () => {
    for (const id of ['cat_eyes_fox_eyes', 'lip_lifting']) {
      const item = PRICING.procedures.find((p) => p.id === id)!;
      expect(item.available, id).toBe(false);
    }
  });

  it('12: every explicit breast-implant brand/variant stays a distinct catalog entry with its own price (never collapsed into one generic line)', () => {
    const variants: [string, number][] = [
      ['breast_aug_silimed_circular', 2950],
      ['breast_lift_silimed_circular', 3500],
      ['breast_aug_motiva_circular', 3200],
      ['breast_aug_motiva_teardrop', 3400],
      ['breast_lift_motiva_circular', 3700],
      ['breast_lift_motiva_teardrop', 3900],
      ['breast_aug_mentor_circular', 3400],
      ['breast_aug_mentor_teardrop', 3600],
      ['breast_lift_mentor_circular', 3900],
      ['breast_lift_mentor_teardrop', 4100],
      ['breast_aug_cereform_circular', 4400],
      ['breast_aug_cereform_teardrop', 4600],
      ['breast_lift_cereform_circular', 4900],
      ['breast_lift_cereform_teardrop', 5000],
    ];
    const ids = new Set(variants.map(([id]) => id));
    expect(ids.size).toBe(variants.length); // every id is unique — none collapsed together
    for (const [id, eur] of variants) {
      const item = PRICING.procedures.find((p) => p.id === id)!;
      expect(item, id).toBeDefined();
      expect(item.price.eur, id).toBe(eur);
    }
  });

  it('13: a Bariatric/Plastic procedure flows through the same per-visit total as any dental procedure — a visit-level override still replaces its calculated total outright', () => {
    const option = baseOption({
      visits: 1,
      procedures: [{ procedureId: 'gastric_sleeve', quantity: 1, finalUnitPriceOverride: null }],
      visit1: { ...emptyVisitInput(), overrideTotal: 5000 },
      visit2: null,
    });
    const result = calculateOption(option, 'EUR', 1);
    expect(result.visits.visit1.calculatedTotal).toBe(2700); // the procedure's own calculated total
    expect(result.visits.visit1.finalTotal).toBe(5000); // the override wins outright, never blended
    expect(result.totals.finalTotal).toBe(5000);
  });

  it('the whole 76-entry catalog carries a unique id and a Bariatric or Plastic category', () => {
    const nonDental = PRICING.procedures.filter((p) => p.category === 'Bariatric' || p.category === 'Plastic');
    expect(nonDental.length).toBe(76);
    expect(new Set(nonDental.map((p) => p.id)).size).toBe(76);
  });

  it('every fixed-price entry is only usable once selected+priced through priceFor, exactly like existing dental procedures', () => {
    const rhino = PRICING.procedures.find((p) => p.id === 'rhinoplasty')!;
    expect(priceFor(rhino.price, 'EUR')).toBe(2900);
    expect(priceFor(rhino.price, 'USD')).toBeNull();
    expect(priceFor(rhino.price, 'AUD')).toBeNull();
  });
});
